apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: restfulapi
  name: restfulapi
  namespace: restfulapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restfulapi
  strategy: {}
  template:
    metadata:
      labels:
        app: restfulapi
    spec:
      containers:
      - image: docker.io/polpinol98/restfulapiapp:1.0.23
        name: restfulapi
        imagePullPolicy: Always
        resources: {}