apiVersion: argoproj.io/v1beta1  # Update if necessary
kind: Application
metadata:
  name: restfulapi-cd
  namespace: argocd
  annotations:
    argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: restfulapi-cd
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: app
    repoURL: https://github.com/PolPinol/RESTfulAPI-CD
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
