apiVersion: v1
kind: Service
metadata:
  labels:
    app: restfulapi
  name: restfulapi
  namespace: restfulapi
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: restfulapi