apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: restfulapi-test
  name: restfulapi-test
  namespace: restfulapi-test
  annotations:
    argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restfulapi-test
  strategy: {}
  template:
    metadata:
      labels:
        app: restfulapi-test
    spec:
      containers:
      - image: docker.io/polpinol98/restfulapiapp:1.0.23
        name: restfulapi-test
        imagePullPolicy: Always
        resources: {}
