apiVersion: v1
kind: Service
metadata:
  name: restfulapi-cd
  namespace: restfulapi-cd
  labels:
    app: restfulapi-cd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: restfulapi-cd
