apiVersion: v1
kind: Service
metadata:
  labels:
    app: RESTfulAPI
  name: RESTfulAPI
  namespace: RESTfulAPI
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: RESTfulAPI