apiVersion: apps/v1
kind: Deployment
metadata:
  name: restfulapi
  namespace: restfulapi
  labels:
    app: restfulapi
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restfulapi
  template:
    metadata:
      labels:
        app: restfulapi
    spec:
      containers:
        - name: restfulapi
          image: docker.io/polpinol98/restfulapiapp:1.0.25
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: {}
