name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GKE_PROJECT_ID }}
        install_components: 'kubectl'

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_CLUSTER_ZONE }}
        project_id: ${{ secrets.GKE_PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f app/RESTfulAPI-namespace.yaml
        kubectl apply -f app/RESTfulAPI-deployment.yaml
        kubectl apply -f app/RESTfulAPI-svc.yaml

    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/restfulapi-cd -n restfulapi-cd

    - name: Get Service External IP
      id: get_external_ip
      run: |
        echo "Waiting for the external IP to be assigned..."
        # Wait until the external IP is assigned, with a timeout of 300 seconds (5 minutes)
        for i in {1..30}; do
          EXTERNAL_IP=$(kubectl get svc restfulapi-cd -n restfulapi-cd -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [ -n "$EXTERNAL_IP" ]; then
            echo "Service External IP: $EXTERNAL_IP"
            echo "::set-output name=external_ip::$EXTERNAL_IP"
            exit 0
          fi
          echo "Attempt $i: External IP not assigned yet. Waiting for 10 seconds..."
          sleep 10
        done
        echo "Failed to retrieve the external IP within the expected time."
        exit 1

    - name: Log External IP
      run: |
        echo "The deployed service is available at: http://$(steps.get_external_ip.outputs.external_ip):8080"