name: E2E and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-22.04

    outputs:
      image_tag: ${{ steps.extract_tag.outputs.image_tag }}
      full_digest: ${{ steps.get_digest.outputs.full_digest }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Extract Docker Tag from Deployment YAML
        id: extract_tag
        shell: bash
        run: |
          # Parse the <TAG> from a line like:  image: docker.io/polpinol98/restfulapiapp:1.0.25
          IMAGE_TAG=$(grep 'image: docker.io/polpinol98/restfulapiapp:' app/RESTfulAPI-deployment.yaml \
            | awk -F ':' '{print $3}')

          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Pull Docker Image Once
        shell: bash
        run: |
          docker pull "docker.io/polpinol98/restfulapiapp:${{ steps.extract_tag.outputs.image_tag }}"

      - name: Get Image Digest
        id: get_digest
        shell: bash
        run: |
          FULL_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' \
            "docker.io/polpinol98/restfulapiapp:${{ steps.extract_tag.outputs.image_tag }}")

          echo "full_digest=$FULL_DIGEST" >> "$GITHUB_OUTPUT"

      - name: Run E2E Tests (external script)
        shell: bash
        run: |
          chmod +x e2e/helloWorld.sh

          ./e2e/helloWorld.sh "docker.io/polpinol98/restfulapiapp:${{ steps.extract_tag.outputs.image_tag }}"

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-22.04
    needs: e2e-test

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GKE_PROJECT_ID }}
          install_components: 'kubectl'

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_ZONE }}
          project_id: ${{ secrets.GKE_PROJECT_ID }}

      - name: Pin the image digest in Deployment YAML
        shell: bash
        run: |
          sed -i "s|image: docker.io/polpinol98/restfulapiapp:.*|image: ${{ needs.e2e-test.outputs.full_digest }}|" \
            app/RESTfulAPI-deployment.yaml

          echo "Deployment pinned to digest: ${{ needs.e2e-test.outputs.full_digest }}"

      - name: Deploy to GKE
        shell: bash
        run: |
          kubectl apply -f app/RESTfulAPI-namespace.yaml
          kubectl apply -f app/RESTfulAPI-deployment.yaml
          kubectl apply -f app/RESTfulAPI-svc.yaml

      - name: Verify Deployment
        shell: bash
        run: |
          kubectl rollout status deployment/restfulapi-cd -n restfulapi-cd
