name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  e2e-test:
    runs-on: ubuntu-22.04
    outputs:
      image_digest: ${{ steps.extract_digest.outputs.image_digest }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Extract image TAG from Deployment file
        id: parse_tag
        run: |
          IMAGE_TAG=$(grep 'image: ' app/RESTfulAPI-deployment.yaml | awk '{print $2}')
          echo "Found image in deployment file: $IMAGE_TAG"
          echo "::set-output name=image_tag::$IMAGE_TAG"

      - name: Pull and Inspect Image
        id: extract_digest
        run: |
          docker pull ${{ steps.parse_tag.outputs.image_tag }}
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ steps.parse_tag.outputs.image_tag }})
          echo "Digest is: $DIGEST"
          echo "::set-output name=image_digest::$DIGEST"

      - name: Run E2E Test with the Immutable Digest
        run: |
          docker run -d --name restfulapi -p 8080:8080 ${{ steps.extract_digest.outputs.image_digest }}
          sleep 5
          curl -f http://localhost:8080/hello
          echo "E2E test success!"
          docker stop restfulapi
          docker rm restfulapi

  deploy:
    runs-on: ubuntu-22.04
    needs: e2e-test
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GKE_PROJECT_ID }}
          install_components: 'kubectl'

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_ZONE }}
          project_id: ${{ secrets.GKE_PROJECT_ID }}

      - name: Deploy Using Immutable Digest
        run: |
          sed -i "s|image: .*|image: ${{ needs.e2e-test.outputs.image_digest }}|" app/RESTfulAPI-deployment.yaml
          
          kubectl apply -f app/RESTfulAPI-namespace.yaml
          kubectl apply -f app/RESTfulAPI-deployment.yaml
          kubectl apply -f app/RESTfulAPI-svc.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/restfulapi-cd -n restfulapi-cd
